### ISSUE TITLE
Failed installation from source -- py_modules?

### ISSUE THREAD

**Issue by profxj** [LSSTDESC/NaMaster#107]
Decided to install from source.  After installing `automake` (an apparent dependency), 
I crashed out after the library build:

```
 /bin/mkdir -p '/home/xavier/Projects/Python/NaMaster/_deps/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c namaster '/home/xavier/Projects/Python/NaMaster/_deps/bin'
libtool: install: /usr/bin/install -c .libs/namaster /home/xavier/Projects/Python/NaMaster/_deps/bin/namaster
 /bin/mkdir -p '/home/xavier/Projects/Python/NaMaster/_deps/include'
 /usr/bin/install -c -m 644 src/namaster.h '/home/xavier/Projects/Python/NaMaster/_deps/include'
make[1]: Leaving directory '/home/xavier/Projects/Python/NaMaster'
Traceback (most recent call last):
  File "setup.py", line 120, in <module>
    ext_modules=[_nmtlib],
  File "/home/xavier/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/xavier/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xavier/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xavier/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 87, in run
    _build.run(self) # RM
  File "/home/xavier/anaconda3/lib/python3.7/site-packages/setuptools/command/build_py.py", line 50, in run
    if not self.py_modules and not self.packages:
  File "/home/xavier/anaconda3/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: py_modules
```

Will start to investigate (have forked the code and will submit a PR if I figure it out). 
Thought I'd raise the Issue now, however.

Am building with Python 3.7 + anaconda on a Linux + Ubuntu 18.0 machine.

I see now that it may matter that I used:

`python setup.py develop`

**Comment by profxj** [comment]
Indeed

`python setup.py install`

ran successfully.  Perhaps someone can advise on how
to use `develop`.  If that is possible..

**Comment by damonge** [comment]
@profxj , sorry for the delay in getting to this one. PR #123 should have fixed this, but let me know if the problem persists.
