### ISSUE TITLE
setup.py missing install_requires

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/NaMaster#138]
`setup.py` does not have a `install_requires` (https://packaging.python.org/discussions/install-requires-vs-requirements/). This causes that `pip` will not wait for its dependencies to be installed before attempting to compile NaMaster.  In [this issue](https://github.com/pypa/pip/issues/5761#issuecomment-418392774) of pip they had a similar problem.

```
2021-08-09T11:13:02.0191548Z ##[group]Run pip install -r requirements.txt
2021-08-09T11:13:02.0192364Z [36;1mpip install -r requirements.txt[0m
2021-08-09T11:13:02.0192792Z [36;1mpip install .[0m
2021-08-09T11:13:02.0233595Z shell: /usr/bin/bash -e {0}
2021-08-09T11:13:02.0234125Z env:
2021-08-09T11:13:02.0234585Z   pythonLocation: /opt/hostedtoolcache/Python/3.6.14/x64
2021-08-09T11:13:02.0235227Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.14/x64/lib
2021-08-09T11:13:02.0235860Z ##[endgroup]
2021-08-09T11:13:05.3623660Z Collecting scipy
2021-08-09T11:13:05.4162134Z   Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
2021-08-09T11:13:06.5538067Z Collecting numpy
2021-08-09T11:13:06.5670107Z   Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
2021-08-09T11:13:06.8798897Z Collecting Jinja2
2021-08-09T11:13:06.8911588Z   Downloading Jinja2-3.0.1-py3-none-any.whl (133 kB)
2021-08-09T11:13:07.0036000Z Collecting pyyaml
2021-08-09T11:13:07.0162713Z   Downloading PyYAML-5.4.1-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
2021-08-09T11:13:07.0926096Z Collecting pyccl==2.1.0
2021-08-09T11:13:07.2576355Z   Downloading pyccl-2.1.0.tar.gz (12.0 MB)
2021-08-09T11:13:32.3790903Z Collecting pytest
2021-08-09T11:13:32.3912146Z   Downloading pytest-6.2.4-py3-none-any.whl (280 kB)
2021-08-09T11:13:32.4344974Z Collecting jupyter
2021-08-09T11:13:32.4455356Z   Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
2021-08-09T11:13:32.5049244Z Collecting sacc
2021-08-09T11:13:32.5171980Z   Downloading sacc-0.4.5.tar.gz (31 kB)
2021-08-09T11:13:32.8181583Z Collecting camb
2021-08-09T11:13:32.8939465Z   Downloading camb-1.3.2.tar.gz (1.6 MB)
2021-08-09T11:13:33.5748786Z Collecting healpy
2021-08-09T11:13:33.8017755Z   Downloading healpy-1.15.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (18.1 MB)
2021-08-09T11:13:34.1822916Z Collecting pymaster
2021-08-09T11:13:34.2628482Z   Downloading pymaster-1.2.tar.gz (1.2 MB)
2021-08-09T11:13:34.6030136Z     ERROR: Command errored out with exit status 1:
2021-08-09T11:13:34.6033839Z      command: /opt/hostedtoolcache/Python/3.6.14/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i3kbmdgv/pymaster_ed122e16a2f84681a823d320c25796cf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i3kbmdgv/pymaster_ed122e16a2f84681a823d320c25796cf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ns3w4lhf
2021-08-09T11:13:34.6037045Z          cwd: /tmp/pip-install-i3kbmdgv/pymaster_ed122e16a2f84681a823d320c25796cf/
2021-08-09T11:13:34.6047501Z     Complete output (5 lines):
2021-08-09T11:13:34.6050716Z     Traceback (most recent call last):
2021-08-09T11:13:34.6052053Z       File "<string>", line 1, in <module>
2021-08-09T11:13:34.6053231Z       File "/tmp/pip-install-i3kbmdgv/pymaster_ed122e16a2f84681a823d320c25796cf/setup.py", line 12, in <module>
2021-08-09T11:13:34.6053882Z         import numpy
2021-08-09T11:13:34.6054487Z     ModuleNotFoundError: No module named 'numpy'
```

**Comment by damonge** [comment]
@carlosggarcia see #143 and let me know if you'd like me to add anything else
