### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/NaMaster#85]
We'd like to be able to install everything automatically (including libsharp and NaMaster's C library) by just running  `python setup.py install`.

This is currently attempted in #84

**Comment by nsevilla** [comment]
On MacOS 10.13 python 2.7, seems to require automake

nsevilla@MacBook-Pro-de-Nacho:/Users/nsevilla/NaMaster$ sudo python setup.py install
Password:
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating pymaster.egg-info
writing pymaster.egg-info/PKG-INFO
writing top-level names to pymaster.egg-info/top_level.txt
writing dependency_links to pymaster.egg-info/dependency_links.txt
writing manifest file 'pymaster.egg-info/SOURCES.txt'
reading manifest file 'pymaster.egg-info/SOURCES.txt'
writing manifest file 'pymaster.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-intel/egg
running install_lib
running build_py
Cloning into 'libsharp'...
remote: Enumerating objects: 1070, done.
remote: Total 1070 (delta 0), reused 0 (delta 0), pack-reused 1070
Receiving objects: 100% (1070/1070), 318.61 KiB | 962.00 KiB/s, done.
Resolving deltas: 100% (736/736), done.
./scripts/install_libsharp.sh: line 13: aclocal: command not found
ERROR: automake not found. Please install this or libsharp will not be installed correctly.
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    ext_modules=[_nmtlib],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 67, in run
    _compile_libsharp() # RM
  File "setup.py", line 54, in _compile_libsharp
    raise DistutilsError('Failed to install libsharp.') # RM
NameError: global name 'DistutilsError' is not defined

**Comment by nsevilla** [comment]
After automake is installed, there is some problem with the gcc library:

nsevilla@MacBook-Pro-de-Nacho:/Users/nsevilla/NaMaster$ sudo python setup.py install
Password:
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing pymaster.egg-info/PKG-INFO
writing top-level names to pymaster.egg-info/top_level.txt
writing dependency_links to pymaster.egg-info/dependency_links.txt
reading manifest file 'pymaster.egg-info/SOURCES.txt'
writing manifest file 'pymaster.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-intel/egg
running install_lib
running build_py
Found automake.
checking for uname... 1
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to support OpenMP... unsupported
Using gcc version 4.2.1
configure: creating ./config.status
config.status: creating config/config.auto
using configuration 'auto'
#  compiling libsharp/sharp_testsuite.c
#  compiling libsharp/sharp_ylmgen_c.c
#  compiling libsharp/sharp.c
#  compiling libsharp/sharp_announce.c
#  compiling libsharp/sharp_geomhelpers.c
#  compiling libsharp/sharp_almhelpers.c
#  compiling libsharp/sharp_core.c
#  compiling libsharp/sharp_legendre.c
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre.c:1319:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
#  compiling libsharp/sharp_legendre_roots.c
#  compiling libsharp/sharp_legendre_table.c
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:56:20: warning: unused function 'build_v4sf' [-Wunused-function]
static inline v4sf build_v4sf (float a, float b, float c, float d)
                   ^
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:58:20: warning: unused function 'read_v4sf' [-Wunused-function]
static inline void read_v4sf (v4sf v, float *a, float *b, float *c, float *d)
                   ^
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:105:20: warning: unused function 'to_V2DF' [-Wunused-function]
static inline V2DF to_V2DF (v2df x)
                   ^
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:107:21: warning: unused function 'to_V2DF2' [-Wunused-function]
static inline V2DF2 to_V2DF2 (v2df2 x)
                    ^
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:109:21: warning: unused function 'to_v2df2' [-Wunused-function]
static inline v2df2 to_v2df2 (V2DF2 X)
                    ^
/Users/nsevilla/NaMaster/_deps/libsharp/libsharp/sharp_legendre_table.c:111:21: warning: unused function 'zero_v2df2' [-Wunused-function]
static inline v2df2 zero_v2df2(void)
                    ^
6 warnings generated.
#  creating library /Users/nsevilla/NaMaster/_deps/libsharp/auto/lib/libsharp.a
#  compiling libfftpack/fftpack.c
#  compiling libfftpack/bluestein.c
#  compiling libfftpack/ls_fft.c
#  creating library /Users/nsevilla/NaMaster/_deps/libsharp/auto/lib/libfftpack.a
#  compiling c_utils/c_utils.c
#  compiling c_utils/walltime_c.c
#  compiling c_utils/memusage.c
#  creating library /Users/nsevilla/NaMaster/_deps/libsharp/auto/lib/libc_utils.a
#  linking C binary /Users/nsevilla/NaMaster/_deps/libsharp/auto/bin/sharp_testsuite
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/nsevilla/NaMaster':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
Traceback (most recent call last):
  File "setup.py", line 109, in <module>
    ext_modules=[_nmtlib],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 68, in run
    _compile_libnmt() # RM
  File "setup.py", line 62, in _compile_libnmt
    raise DistutilsError('Failed to compile C library.') # RM
NameError: global name 'DistutilsError' is not defined

**Comment by damonge** [comment]
Thanks a lot @nsevilla !
I'll add a check for automake.

The second one is kind of weird. Can you share the config.log file?

**Comment by xzackli** [comment]
I encountered basically no problems on Della and Tiger at Princeton. There was briefly an issue with something like `undefined reference to `rpl_malloc'`, which some googling implied was some autotools issue. I ended up running

```
ac_cv_func_malloc_0_nonnull=yes ./configure --prefix=...
```
to get a working installation.
